### ISSUE TITLE
how to pass answer from one menu to another

### ISSUE THREAD

**Issue by phamdt** [dixonwille/wmenu#15]
i have a wizard with multiple questions and therefore multiple menus. i want subsequent menus to depend on data from previous menus. how could i achieve this?

**Comment by dixonwille** [comment]
@phamdt Sorry I am just now reading this. If you give me to end of the day I will get back to you. I never got notified.

**Comment by phamdt** [comment]
thanks!

**Comment by dixonwille** [comment]
@phamdt sorry for the long wait. Work has me busy.

I just pushed up an example folder that goes through one way of doing subsequent menus. There is more than one way to do it. I have done it a different way for tools at my workplace (cannot share those I am sorry).

Another way is instead of a single action for all options, give each option a different action. Each different action would generate a different menu and run it similar to how the single action for all choices work. The beauty of programming is there is always more than one answer. Let me know if this helps.

**Comment by phamdt** [comment]
Will take a look. Thanks!
