### ISSUE TITLE
Display menu options from 1 up

### ISSUE THREAD

**Issue by Tronchoo** [dixonwille/wmenu#17]
Display menu options from 1 and up instead of the current state that the options counting starts from 0

**Comment by RonQedit** [comment]
+1

**Comment by dixonwille** [comment]
@Tronchoo Cool. Will look into this.

**Comment by dixonwille** [comment]
So I have a PR out there but I am trying to decide on the new version of WMenu. v4.0.2 is the latest. If I say v4.1.0 that is saying that code already using this package is compatible with this new version (which not all code will be). Depending on how it was developed it will break (if they use IDs for example). But all method signatures (except for one) has stayed the same. What do you think?

**Comment by RonQedit** [comment]
@dixonwille Working great, no more keyboard-distance between the first two options :)

**Comment by akerl** [comment]
As a heads up, I just got burned by this because after this change, "ID" no longer lines up with the display. So if a user picks "2", I have to math that before using it as an ID in the options list.

This is pretty hard to handle in a backwards compatible way, since depending on the wmenu version I might or might not have to subtract 1 from the user input. Would it make more sense to have IDs be incremented by one so they always line up with what is displayed?

**Comment by dixonwille** [comment]
@akerl I may have to create another package... This was one of my first GoLang packages so I was just learning. It will have GoMod support and try and cover all issues on in this package and hopefully in a better backwards compatible manner. It would make sense with what you are saying to have them lined up or use a different ID method?
